- name: Install Dependencies
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - python3-pycurl
    - epel-release

- name: Install PIP
  yum:
    name: python3-pip
    state: present

- name: Upgrade pip3
  pip:
    name: pip
    executable: pip3
    state: latest
    extra_args: --upgrade --ignore-installed

- name: Install RMON Agent python requirements
  ansible.builtin.pip:
    executable: /usr/local/bin/pip3
    requirements: /var/lib/rmon/rmon-agent/requirements.txt
