- name: Install Pycurl
  ansible.builtin.apt:
    name:
    - python3-pip
    - python3-pycurl
    state: present

- name: Upgrade pip3
  pip:
    name: pip
    executable: pip3
    state: latest
    extra_args: --upgrade --break-system-packages

- name: Install RMON Agent python requirements
  ansible.builtin.pip:
    requirements: /var/lib/rmon/rmon-agent/requirements.txt
    extra_args: --break-system-packages
