- name: Install Pycurl
  ansible.builtin.apt:
    name:
    - python3-pip
    - python3-pycurl
    state: present

- name: Upgrade pip3 for new Debian
  pip:
    name: pip
    executable: pip3
    state: latest
    extra_args: --upgrade --break-system-packages
  ignore_errors: true

- name: Install RMON Agent python requirements for new Debian
  ansible.builtin.pip:
    requirements: /var/lib/rmon/rmon-agent/requirements.txt
    extra_args: --break-system-packages
  ignore_errors: true

- name: Upgrade pip3 for old Debian
  pip:
    name: pip
    executable: pip3
    state: latest
    extra_args: --upgrade
  ignore_errors: true

- name: Install RMON Agent python requirements for old Debian
  ansible.builtin.pip:
    requirements: /var/lib/rmon/rmon-agent/requirements.txt
  ignore_errors: true
