- name: Install Dependencies
  ansible.builtin.apt:
    name:
    - python3-pip
    - python3-pycurl
    - mtr-tiny
    state: present
    update_cache: true

- name: Upgrade pip3 for new Debian
  pip:
    name: pip
    state: latest
    extra_args: --upgrade --break-system-packages
  register: pip_upgrade1_result
  ignore_errors: true

- name: Install RMON Agent python requirements for new Debian
  ansible.builtin.pip:
    requirements: /var/lib/rmon/rmon-agent/requirements.txt
    extra_args: --break-system-packages
  when: pip_upgrade1_result is succeeded
  register: pip_install1_result
  ignore_errors: true

- name: Upgrade pip3 for old Debian
  pip:
    name: pip
    executable: pip3
    state: latest
    extra_args: --upgrade
  when: pip_upgrade1_result is failed
  ignore_errors: true

- name: Install RMON Agent python requirements for old Debian
  ansible.builtin.pip:
    requirements: /var/lib/rmon/rmon-agent/requirements.txt
  when: pip_install1_result is failed
  ignore_errors: true
